owner: benjaminsimier
repo: uptime

sites:
  - name: Benjamin Simier
    url: https://www.benjaminsimier.com
  - name: Tanzanie Adventure Safaris
    url: https://www.tanzanieadventuresafaris.co.tz

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
